version: "3.8"
services:

  api_server:
    build: ./blogapiservice/blogapiservice 
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb

  auth_server:
    build: ./AuthServerService
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: springversion
      MYSQL_USER: tom123
      MYSQL_PASSWORD: tom123
      MYSQL_ROOT_PASSWORD: tom123


#version: "3.9"
#services:
#  db:
#    platform: linux/x86_64
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456tg
#      - MYSQL_DATABASE=springversion
#    ports:
#      - "5432:5432"
#
#  api:
#    platform: linux/x86_64
#    build: ./
#    ports:
#      - "8080:8080"
#    restart: always
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:5432/springversion
#      - DATABASE_USERNAME=root
#      - DATABASE_PASSWORD=123456tg
#    volumes:
#      - db-data:/var/lib/mysql/data
#    depends_on:
#      - db
#
#volumes:
#  db-data: